### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by ncuillery** [lincolnloop/crossing#7]
Hi,

I encounter a problem with trailing slashes. If I declare 

``` javascript
urls.load({
  mypage: '/mypage'
});

urls.resolve('/mypage') // --> resolve mypage
urls.resolve('/mypage/') // --> undefined
```

The react-router doesn't care about trailing slash : https://github.com/reactjs/react-router/blob/a25d9a67ee366b172fdb8694b8206afea6f3f6a8/modules/isActive.js#L53-L61

And it causes some problems because I use `urls.resolve` inside [match](https://github.com/reactjs/react-router/blob/master/docs/API.md#match-routes-location-history-options--cb). `match` matches the route with trailing slash and Crossing don't.

I think an additional option to the costructor (like this: `new Crossing(urlParamRegexp, matchTrailingSlash)`) is the best way to handle that without any breaking changes.

Are you guys interested in a PR ?

**Comment by mlouro** [comment]
Hi,

Yeah, feel free to do a PR and we'll merge it in. 

Thanks!
